For me (macosx with canopy), I get the following because png isn't a valid backend.
File
  "/Applications/Canopy.app/appdata/canopy-1.0.1.1189.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/rcsetup.py",
  line 51, in __call__
      % (self.key, s, self.valid.values()))
      ValueError: Unrecognized backend string "png": valid strings are ['pgf',
      'cairo', 'MacOSX', 'CocoaAgg', 'gdk', 'ps', 'GTKAgg', 'GTK', 'QtAgg',
      'template', 'FltkAgg', 'emf', 'GTK3Cairo', 'GTK3Agg', 'WX', 'Qt4Agg',
      'TkAgg', 'agg', 'svg', 'GTKCairo', 'WXAgg', 'pdf']

Agg is the backend that allows png as a savefig option.